"""add diagnostic_questions table

Revision ID: 6cdd3e295e9e
Revises: 
Create Date: 2026-08-18 18:42:17.497181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdd3e295e9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False, comment='题目文本'),
    sa.Column('options', sa.JSON(), nullable=False, comment="选项列表，如 ['A. ...', 'B. ...']"),
    sa.Column('answer', sa.String(length=10), nullable=False, comment='正确答案，如 A/B/C/D'),
    sa.Column('tag', sa.String(length=50), nullable=False, comment="知识点标签，如 '数据类型'"),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False, comment='教程（关卡）ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目 ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'question_id', name='uq_lesson_question')
    )
    op.create_index(op.f('ix_lesson_questions_lesson_id'), 'lesson_questions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_questions_question_id'), 'lesson_questions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_questions_question_id'), table_name='lesson_questions')
    op.drop_index(op.f('ix_lesson_questions_lesson_id'), table_name='lesson_questions')
    op.drop_table('lesson_questions')
    op.drop_table('diagnostic_questions')
    # ### end Alembic commands ###
